# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-09 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20190322_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='ser',
            new_name='user',
        ),
    ]
